# -*- coding: utf-8 -*-
"""classification_utils.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yGDnDUcQnejNwuA1HEftYG1wcyNfweop

このファイルは：

分類タスク（分類モデル用）

Google Drive連携完備

XGBoost / RandomForest / Logistic / SVM対応

ハイパーパラメータチューニング可能

モデル評価（Accuracy、F1、ROC、PR、混同行列）

SHAP解析（Summary, Waterfall, 3D）

ファイルアップロード支援あり
"""

# ================================
# インポートと環境設定
# ================================

import os
import joblib
import logging
import pandas as pd
import numpy as np
import shap
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.metrics import (accuracy_score, confusion_matrix, classification_report,
                             roc_curve, auc, precision_recall_curve, f1_score)
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from google.colab import drive
from google.colab import files

from typing import Any, Dict, List, Optional, Tuple, Union

# ログ設定
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)
# ================================
# Google Drive連携・ファイル保存・読込
# ================================

def mount_drive() -> None:
    """Google Driveをマウントする"""
    try:
        drive.mount('/content/drive')
        logger.info("✅ Google Driveマウント成功")
    except Exception as e:
        logger.error(f"❌ Driveマウント失敗: {e}")

def save_to_drive(data: Any, relative_path: str) -> None:
    """データをGoogle Driveに保存する"""
    try:
        full_path = os.path.join('/content/drive/MyDrive/', relative_path)
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        joblib.dump(data, full_path)
        logger.info(f"✅ 保存成功: {full_path}")
    except Exception as e:
        logger.error(f"❌ 保存失敗: {e}")

def load_from_drive(relative_path: str) -> Any:
    """Google Driveからデータをロードする"""
    try:
        full_path = os.path.join('/content/drive/MyDrive/', relative_path)
        return joblib.load(full_path)
    except Exception as e:
        logger.error(f"❌ ロード失敗: {e}")
        return None
# ================================
# データロード・前処理・分割
# ================================

def load_dataset(dataset_name: str) -> Tuple[pd.DataFrame, pd.Series, Optional[np.ndarray]]:
    """
    標準データセットをロードする（digits, iris, breast_cancer, wine対応）
    """
    from sklearn import datasets
    try:
        if dataset_name == 'digits':
            data = datasets.load_digits()
            return pd.DataFrame(data.data), pd.Series(data.target), data.images
        elif dataset_name == 'iris':
            data = datasets.load_iris()
            return pd.DataFrame(data.data, columns=data.feature_names), pd.Series(data.target), None
        elif dataset_name == 'breast_cancer':
            data = datasets.load_breast_cancer()
            return pd.DataFrame(data.data, columns=data.feature_names), pd.Series(data.target), None
        elif dataset_name == 'wine':
            data = datasets.load_wine()
            return pd.DataFrame(data.data, columns=data.feature_names), pd.Series(data.target), None
        else:
            logger.error(f"未対応のデータセット: {dataset_name}")
            return None, None, None
    except Exception as e:
        logger.error(f"データセットロード失敗: {e}")
        return None, None, None

def load_csv_data(file_path: str, target_column: str, features_to_drop: Optional[List[str]] = None) -> Tuple[pd.DataFrame, pd.Series]:
    """
    CSVファイルからデータをロードする
    """
    try:
        if not os.path.exists(file_path) and '/content/drive' not in file_path:
            file_path = os.path.join('/content/drive/MyDrive/', file_path)

        df = pd.read_csv(file_path)
        logger.info(f"📊 データ概要:\n{df.describe().T}")

        if features_to_drop:
            df = df.drop(columns=features_to_drop)

        if target_column not in df.columns:
            logger.error(f"目的変数 '{target_column}' が存在しません")
            return None, None

        X = df.drop(columns=[target_column])
        y = df[target_column]

        cat_columns = X.select_dtypes(include=['object']).columns
        if len(cat_columns) > 0:
            logger.info(f"カテゴリ変数検出: {list(cat_columns)}")

        return X, y
    except Exception as e:
        logger.error(f"CSVロード失敗: {e}")
        return None, None

def preprocess_and_split(X: pd.DataFrame, y: pd.Series,
                          test_size: float = 0.2,
                          validation_size: float = 0.0,
                          random_state: int = 42) -> Union[
                              Tuple[pd.DataFrame, pd.DataFrame, pd.Series, pd.Series],
                              Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.Series, pd.Series, pd.Series]]:
    """
    データセットを訓練・検証・テストに分割する
    """
    if X is None or y is None:
        raise ValueError("入力データがNoneです")

    categorical_cols = X.select_dtypes(include=['object', 'category']).columns
    if len(categorical_cols) > 0:
        logger.info(f"カテゴリ変数エンコード: {list(categorical_cols)}")
        X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

    if X.isnull().sum().sum() > 0:
        logger.info("欠損値を中央値で補完")
        X = X.fillna(X.median())

    if validation_size > 0:
        X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=test_size + validation_size, random_state=random_state)
        valid_ratio = validation_size / (test_size + validation_size)
        X_valid, X_test, y_valid, y_test = train_test_split(X_temp, y_temp, test_size=1 - valid_ratio, random_state=random_state)
        return X_train, X_valid, X_test, y_train, y_valid, y_test
    else:
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=random_state)
        return X_train, X_test, y_train, y_test
# ================================
# モデル学習・ハイパーパラメータチューニング
# ================================

def train_model(X_train: pd.DataFrame, y_train: pd.Series,
                model_type: str = "xgboost",
                params: Optional[Dict] = None,
                use_grid_search: bool = False,
                param_grid: Optional[Dict] = None,
                cv: int = 5) -> Any:
    """
    指定されたモデルで学習する
    """
    logger.info(f"🔄 モデル学習開始: {model_type}")

    if model_type.lower() == "xgboost":
        model = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
    elif model_type.lower() == "random_forest":
        model = RandomForestClassifier()
    elif model_type.lower() == "logistic":
        model = LogisticRegression(max_iter=1000)
    elif model_type.lower() == "svm":
        model = SVC(probability=True)
    else:
        logger.error(f"❌ 未対応のモデルタイプ: {model_type}")
        return None

    if params:
        model.set_params(**params)

    if use_grid_search and param_grid:
        logger.info("🔍 GridSearchCVでハイパーパラメータチューニング")
        model = GridSearchCV(model, param_grid, cv=cv, n_jobs=-1, verbose=1)

    model.fit(X_train, y_train)
    logger.info("✅ モデル学習完了")
    return model

def perform_cross_validation(model: Any, X: pd.DataFrame, y: pd.Series, cv: int = 5) -> Dict[str, float]:
    """
    クロスバリデーションスコアを計算する
    """
    logger.info(f"🔄 {cv}-foldクロスバリデーション実行")
    scores = cross_val_score(model, X, y, cv=cv)
    return {
        "mean_score": np.mean(scores),
        "std_score": np.std(scores),
        "scores": scores.tolist()
    }
# ================================
# モデル評価
# ================================

def evaluate_model(model: Any, X_test: pd.DataFrame, y_test: pd.Series,
                   plot_confusion: bool = True, plot_roc: bool = True, plot_pr: bool = True) -> None:
    """
    テストデータを用いてモデルを評価する
    """
    preds = model.predict(X_test)
    probas = model.predict_proba(X_test)[:, 1] if hasattr(model, "predict_proba") else None

    acc = accuracy_score(y_test, preds)
    f1 = f1_score(y_test, preds, average="macro")

    logger.info(f"🎯 Accuracy: {acc:.4f}")
    logger.info(f"🎯 F1 Score (Macro): {f1:.4f}")
    print(classification_report(y_test, preds))

    if plot_confusion:
        cm = confusion_matrix(y_test, preds)
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
        plt.title("Confusion Matrix")
        plt.xlabel("Predicted")
        plt.ylabel("Actual")
        plt.show()

    if probas is not None and plot_roc:
        fpr, tpr, thresholds = roc_curve(y_test, probas)
        roc_auc = auc(fpr, tpr)
        plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.2f}")
        plt.plot([0, 1], [0, 1], linestyle='--')
        plt.xlabel("False Positive Rate")
        plt.ylabel("True Positive Rate")
        plt.title("ROC Curve")
        plt.legend()
        plt.show()

    if probas is not None and plot_pr:
        precision, recall, thresholds = precision_recall_curve(y_test, probas)
        plt.plot(recall, precision)
        plt.xlabel("Recall")
        plt.ylabel("Precision")
        plt.title("Precision-Recall Curve")
        plt.show()
# ================================
# SHAP解析
# ================================

def explain_shap(model: Any, X_test: pd.DataFrame, model_type: str = "tree",
                 plot_summary: bool = True, plot_waterfall: bool = True, row_index: int = 0) -> shap.Explanation:
    """
    テストデータに対するSHAP解析を行う
    """
    try:
        if model_type == "tree":
            explainer = shap.TreeExplainer(model)
        else:
            explainer = shap.Explainer(model.predict, X_test)

        shap_values = explainer(X_test)

        if plot_summary:
            shap.summary_plot(shap_values.values, features=X_test, feature_names=X_test.columns)

        if plot_waterfall:
            shap.plots.waterfall(shap_values[row_index])

        return shap_values
    except Exception as e:
        logger.error(f"❌ SHAP解析失敗: {e}")
        return None

def plot_shap_3d(shap_values: shap.Explanation, X_test: pd.DataFrame,
                 feature_x: str, feature_y: str, shap_feature: Optional[str] = None) -> None:
    """
    2軸特徴量とSHAP値を3Dプロット
    """
    try:
        if shap_feature:
            shap_z = shap_values.values[:, X_test.columns.get_loc(shap_feature)]
        else:
            shap_z = shap_values.values.mean(axis=1)

        df = pd.DataFrame({
            "X": X_test[feature_x],
            "Y": X_test[feature_y],
            "SHAP": shap_z
        })

        fig = px.scatter_3d(df, x="X", y="Y", z="SHAP", color="SHAP", opacity=0.7)
        fig.show()
    except Exception as e:
        logger.error(f"❌ 3D SHAPプロット失敗: {e}")
# ================================
# ファイルアップロード支援
# ================================

def upload_file_from_local() -> Dict[str, Any]:
    """
    ローカルPCからファイルをアップロードする
    """
    logger.info("📂 ローカルからファイルをアップロードしてください")
    uploaded = files.upload()
    logger.info(f"✅ アップロードファイル: {list(uploaded.keys())}")
    return uploaded